services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=8082
      - KEYCLOAK_CLIENT_ID=demo-resourceserver
      - KEYCLOAK_CLIENT_SECRET=COY1dxTj89CMtEIvAQ7b7K24OrmxKexf
      - AUTH_SERVER_URL=http://keycloak:8080/realms/demo-api/protocol/openid-connect/
      - AUTH_INTROSPECTION_ENDPOINT=token/introspect

  # clientはリダイレクト等々認証の都合があるので localhost と keycloakというドメインを共存させられず、ローカルではコンテナの一部としては動かせない make serveする

  envoy:
    image: envoyproxy/envoy:v1.19.0
    platform: linux/x86_64
    ports:
      - '8082:80'
    volumes:
      - ./api-proxy/envoy.local.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - api
    environment:
      - 'ENVOY_UID=0'
    command: "envoy -c /etc/envoy/envoy.yaml --log-level debug"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB : mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_LOG_LEVEL: DEBUG
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - keycloak-db

  keycloak-db:
    image: mysql:8.0.33
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  mysql_data:
      driver: local