services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: start-dev
  
  web-front:
    build: 
      context: ./web-front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
